// app/layout.tsx
import type { Metadata, Viewport } from "next";
import Script from "next/script";
import "./globals.css";

const siteUrl = "https://www.hbarcoinflip.com";
const title = "HBAR Coin Flip — Provably Fair Hedera Coin Flip Game";
const description =
  "Play a Hedera coin flip with HBAR. Provably fair coinflip game on Hedera Hashgraph — fast finality, low fees, and results verifiable on HashScan.";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: title,
    template: "%s | HBAR Coin Flip",
  },
  description,
  applicationName: "HBAR CoinFlip",
  alternates: {
    canonical: "/", // renders <link rel="canonical" href="https://www.hbarcoinflip.com/" />
  },
  robots: {
    index: true,
    follow: true,
  },
  themeColor: "#000000",
  manifest: "/site.webmanifest", // served from /public
  icons: {
    icon: [
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
      { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180", type: "image/png" }],
  },
  openGraph: {
    type: "website",
    url: siteUrl,
    title,
    description:
      "Play a Hedera coin flip with HBAR. Provably fair coinflip game on Hedera Hashgraph — verify every result on HashScan.",
    images: [{ url: "/og_image.png" }],
  },
  twitter: {
    card: "summary_large_image",
    site: siteUrl,
    title,
    description:
      "Play a Hedera coin flip with HBAR. Provably fair coinflip game on Hedera Hashgraph — verify every result on HashScan.",
    images: ["/og_image.png"],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const GA_MEASUREMENT_ID = "G-JCSMDPQ4P2";

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Hedera Coin Flip (HBAR CoinFlip)",
    url: siteUrl,
    description:
      "A Hedera coin flip game that uses HBAR. Provably fair with all outcomes verifiable on HashScan.",
    applicationCategory: "Game",
    operatingSystem: "Web",
    author: { "@type": "Organization", name: "HBAR CoinFlip" },
    image: `${siteUrl}/og_image.png`,
  };

  return (
    <html lang="en">
      <body>
        {children}

        {/* JSON-LD */}
        <Script
          id="jsonld-webapp"
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
          strategy="afterInteractive"
        />

        {/* Google Analytics */}
        <Script
          src={`https://www.googletagmanager.com/gtag/js?id=${GA_MEASUREMENT_ID}`}
          strategy="afterInteractive"
        />
        <Script id="ga-gtag" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${GA_MEASUREMENT_ID}');
          `}
        </Script>
      </body>
    </html>
  );
}


// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// // const geistSans = Geist({
// //   variable: "--font-geist-sans",
// //   subsets: ["latin"],
// // });

// // const geistMono = Geist_Mono({
// //   variable: "--font-geist-mono",
// //   subsets: ["latin"],
// // });

// export const metadata: Metadata = {
//   title: "HBAR Coinflip — Stats",
//   // description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body className="bg-neutral-50 text-neutral-900 antialiased">
//         {/* <div className="mx-auto max-w-7xl p-4 md:p-8">{children}</div> */}
//         <div>{children}</div>
//       </body>
//     </html>
//   );
// }
